config/routes.rb
Videos::Application.routes.draw do
  resources :kinds

  devise_for :users

  resources :videos

  resources :statuses

  resources :tracks

root :to => 'videos#index'

end

app/models/kind.rb
class Kind < ActiveRecord::Base
  attr_accessible :name
  has_many :statuses, class_name: 'Status'
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kinds }
    end
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
    @kind = Kind.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kind }
    end
  end

  # GET /kinds/new
  # GET /kinds/new.json
  def new
    @kind = Kind.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kind }
    end
  end

  # GET /kinds/1/edit
  def edit
    @kind = Kind.find(params[:id])
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(params[:kind])

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render json: @kind, status: :created, location: @kind }
      else
        format.html { render action: "new" }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kinds/1
  # PUT /kinds/1.json
  def update
    @kind = Kind.find(params[:id])

    respond_to do |format|
      if @kind.update_attributes(params[:kind])
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1
  # DELETE /kinds/1.json
  def destroy
    @kind = Kind.find(params[:id])
    @kind.destroy

    respond_to do |format|
      format.html { redirect_to kinds_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_for @kind, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                kinds_path, :class => 'btn' %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kinds/index.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped table-condensed table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= link_to kind.id, kind_path(kind) %></td>
        <td><%= kind.name %></td>
        <td><%=l kind.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_kind_path(kind), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      kind_path(kind),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_kind_path,
            :class => 'btn btn-primary' %>

app/views/kinds/new.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kinds/show.html.erb
<%- model_class = Kind -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @kind.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              kinds_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_kind_path(@kind), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              kind_path(@kind),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>