config/routes.rb
Videos::Application.routes.draw do
  resources :kinds

  devise_for :users

  resources :videos

  resources :statuses

  resources :tracks

root :to => 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :track, class_name: 'Track'
  has_many :statuses, class_name: 'Status'
  attr_accessible :current, :track_id, :name, :location, :dateFilmed, :existing_status_attributes
  accepts_nested_attributes_for :statuses
	def track_name
		track.name if track
	end

	def update_complete
		i=0
		self.statuses.each do |f|
			if f.completed==false then
				i=1
			end
		end
		if i==0 then
			self.current="Complete!"
			self.save!
		else
			self.current="Incomplete"
			self.save!
		end
	end
def new_status_attributes=(status_attributes)
    status_attributes.each do |attributes|
      statuses.build(attributes)
    end 
  end

  def existing_status_attributes=(status_attributes)
    statuses.reject(&:new_record?).each do |status|
      attributes = status_attributes[status.id.to_s]
      if attributes['_delete'] == '1'
        statuses.delete(status)
      else
        status.attributes = attributes
      end
    end
  end

  private

  def save_statuses
    statuses.each do |status|
      status.save!
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])
    Kind.all.each do |f|
      @video.statuses.new(:kind =>f, :kind_id=>f.id,:progress =>"",:comment =>"", :time_comp => nil, :completed =>false, :video_id =>@video.id)
    end
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def nested
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for @video, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
      <div class="control-group">
    <%= f.label :dateFilmed, :class => 'control-label' %>
    <div class="controls">
<div class="well">
  <div id="datetimepicker1" class="input-append date">
    <input data-format="dd/MM/yyyy hh:mm:ss" type="text" id="video_dateFilmed" name="video[dateFilmed]"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
</div>
<script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>


    </div>
  </div>
    <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :location, ["Mission","Russian Hill","Marina","Nob Hill", "Pacific Heights", "Presidio"],:class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :track, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :track_id, Track.all, :id, :name, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/videos/_quickedit.html.erb
<%= form_for @video  do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
     <div class="controls">
    <%= f.text_field :name, :class => 'text_field'%>
  </div>
    </div>
  <div class="control-group">
    <%= f.label :current, :class => 'control-label' %> <div class="controls">
    <%= f.text_field :current, :disabled=>true, :class => 'text_field'%>
  </div>
    </div>
  <div class="control-group">
    <%= f.label :track, :class => 'control-label' %> <div class="controls">
    <%= f.collection_select :track_id, Track.all, :id, :name, :class => 'number_field'%>
  </div>
    </div>

  <% @video.statuses.each do |status| %>
     <% new_or_existing = status.new_record? ? 'new' : 'existing' %> 
    <% prefix = "video[#{new_or_existing}_status_attributes][]" %> 
    
    <%= fields_for prefix,status do |status_form| %>
        <div class="row">
         <div class="span2"> <%= status_form.label :completed, status.kind_name %></div>
         <div class="span1">
          <%= status_form.check_box :completed %></div>
<div class="span1">
     <%= status_form.select :progress, ["","Copying","Processing","DONE","ISSUE"],:class => 'number_field' %></div>
          <div class="span3">
          <%=status_form.text_field :comment, :class=>"text_field"%></div>
   
        </div>
    <% end %>
  <% end %>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                videos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'quickedit' %>

app/views/videos/index.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped table-condensed table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
       <th><%= model_class.human_attribute_name(:name) %></th>
       <th><%= model_class.human_attribute_name(:current) %></th>
       <th><%= model_class.human_attribute_name(:dateFilmed) %></th>
       <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:track_id) %></th>
     <th><%=t '.actions', :default => t("helpers.actions") %></th>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.id, video_path(video) %></td>
        <td><%= video.name %></td>
        <td><%= video.current %></td>
        <td><%= video.dateFilmed.try(:strftime,"%a, %b %d, %I:%M %p") %></td>
        <td><%= video.location %></td>
        <td><%= video.track_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_video_path(video), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      video_path(video),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_video_path,
            :class => 'btn btn-primary' %>

app/views/videos/new.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/videos/show.html.erb
<%- model_class = Video -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @video.name %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:current) %>:</strong></dt>
  <dd><%= @video.current %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dateFilmed) %>:</strong></dt>
  <dd><%= @video.dateFilmed.try(:strftime,"%a, %b %d, %I:%M %p") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @video.location %></dd>
  
  <dt><strong><%= model_class.human_attribute_name(:track_id) %>:</strong></dt>
  <dd><%= @video.track_name %></dd>

</dl>
<% if @video.statuses %>
<table class="table table-condensed table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:kind_name) %></th>
       <th><%= model_class.human_attribute_name(:progress) %></th>
     <th><%= model_class.human_attribute_name(:comment) %></th>
      <th><%= model_class.human_attribute_name(:time_comp) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @video.statuses.each do |status| %>
      <% if status.progress=="" then %>
      <%= "<tr style=\" background-color: #FFFFFF\">".html_safe%>
      <% elsif status.progress=="Copying" then %>
        <%= "<tr style=\" background-color: #FFFF4D\">".html_safe%>
      <% elsif status.progress=="Processing" then %>
        <%= "<tr style=\" background-color: #3399FF\">".html_safe%>
      <% elsif status.progress=="DONE" then %>
        <%= "<tr style=\" background-color: #94FF94\">".html_safe%>
          <% elsif status.progress=="ISSUE" then %>
        <%= "<tr style=\" background-color: #FF3030\">".html_safe%>
     <% else %>
        <%= "<tr>".html_safe%>
        <%end%>
        <td><%= link_to status.id, status_path(status) %></td>
        <td><%= status.kind_name %></td>
        <td><%= status.progress %></td>
        <td><%= status.comment %></td>
        <td><%= status.time_comp.try(:strftime,"%a, %b %d, %I:%M %p") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_status_path(status), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      status_path(status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
  	<b>No statuses</b>
<%end%>
<div class="form-actions">
  <%= link_to "Videos",
              videos_path, :class => 'btn'  %>
  <%= link_to "Statuses",
              statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_video_path(@video), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              video_path(@video),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>